## What are vectors?
A vector such as $\begin{bmatrix}-2\\3 \end{bmatrix}$ Here -2 represent the x-axis and 3 represent y-axis or in other words `-2` is the magnitude (how long it is) and `3` is the direction.
whereas 3D vector add an additional z-axis which can be used e.g. to locate the point in space or we can use it in velocity etc.
A real-life example of using a 3D velocity vector to describe the motion of an object is the motion of an airplane. An airplane can be moving in the $x$ direction (forward), the $y$ direction (left or right), and the $z$ direction (up or down), all at the same time. By representing the velocity of the airplane as a 3D vector, we can describe its speed and direction of motion in three-dimensional space.

In this way, 3D velocity vectors are useful in fields such as physics and engineering, where it is important to analyze and describe the motion of objects in three-dimensional space.
***



## What are Scalars?
Changing and squishing and sometimes the direction of the vector is called `scalling` and when we encounter numbers like (1, 1\3, -1.8) etc is called scalars. 
In simple terms a vector is an ordered list of numbers e.g.
$\begin{pmatrix}a1 \\ a2\\ a3\\ \vdots \\ a_n \end{pmatrix} \quad n-dimensional matrix$

To go from point B to point A we will need to take 4 steps to the right and 2 steps up.

This defines the vector $\vec{x}=\begin{bmatrix}4\\2 \end{bmatrix}$
Scalar is single value like temperature, force, direction but only one of it whereas Vector made up of combining multiple scalars. e.g force and direction.
Below single value represent scalar while combining those values representing the vector.
**Radian and Degree are both used to measure angle 1-Radian = 180-Degree


<div style="display: flex;">
  <img src="https://i.postimg.cc/28d9C4Q5/delete.png" style='width:400px'/>
  <img src="https://riseandsine.com/wp-content/uploads/2021/10/radian-vs.-degree.png"/ style='width:400px'>
</div>

#### To find circumference of something formula: $c=2\pi r$



### Magnitude and Direction
Each vector holds the magnitude as well as the direction of the movement.

Let's calculate both for: $\vec{x}=\begin{bmatrix}4\\2 \end{bmatrix}$

<div>
<img src="https://pt3mathematics.blog.onlinetuition.com.my/wp-content/uploads/sites/6/2015/01/Picture3.png" style='width:400px')/>
</div>

<b>Pythagorean theorem said that summing both a & b leg of right angle triangle is equal to it's hypotenuse.
   e.g. We can apply this on Tree where a (height of tree) & b (base of tree) now puting this into the above equation will gives
    us the trunk(tanna in pashto) size of the tree.

In our example the magnitude will be calculated the following way:

$||\vec x|| = \sqrt{4^2 + 2^2}$

Where 4 is the horizontal (base of tree )component of the vector and 2 is the vertical (height of tree).

$\theta$ is a symbol used to represent the size of the angle.


<p style="background-color: #ccffcc; padding:24px">$\therefore$ We take the square root of the above pythagorean theorem because we want the magnitude to be positive not negative because if we take square root of negative numbers it will gives us error.</p>


### Scalar by vector multiplication
To scale up or down the vector we need alpha (which is a scalar and it only have magnitude not direction bcz it's 1D) to multiply with vector e.g.

$\alpha\vec{x}=\begin{bmatrix}4\\2 \end{bmatrix} \text{multipy alpha with vector}\Rightarrow \begin{bmatrix} \alpha 4 \\ \alpha2\end{bmatrix} \text{Here alpha can be any scalar e.g. [2]}$ 


### Linear Combinations, Span and Basis Vectors. Part 1
The "Span" of $\vec v$ and $\vec w$ is the set of all their linear combinations.

Above these 'v' and 'w' vector is called basis vectors.

$a\vec v + b\vec w\\ \text{Let a and b vary over all real numbers.}$ 
Here above we have two scalars {a,b} where each of the scalar would be multiplied to the vector and then add all those in one single vector.
**Linear combination**: Means that when we multiply and add those vectors it can gives us any possible linear combination.
Here in the below the red dot's area would contain all the possilble linear combination of these vector.
[![delete.png](https://i.postimg.cc/MKMzCMxP/delete.png)](https://postimg.cc/VdwyMNJn)

## Linearly dependent & Linearly Independent
When one vector can be defined as a linear combination of the other vectors, they are a set of linearly dependent vectors.
e.g. 

$\vec v_1 = \begin{bmatrix}1\\2\\3\end{bmatrix}$
$\vec v_2 = \begin{bmatrix}2\\2\\2\end{bmatrix}$
$\vec v_3 = \begin{bmatrix}8\\8\\8\end{bmatrix}$

For instance: if we multiply a 4 scalar with $v_2$ then we get $v_3$ so both of these are linearly dependent vectors.

$$4\vec v_2 \Rightarrow \vec v_3$$



In our example:
* ${v_1,v_2}\text{ is linearly independent vectors.}$
* ${v_1,v_3}\text{ is linearly independent vectors.}$
and
* ${\underline{v_2,v_3}}\text{ is linearly dependent vectors.}$


$\begin{bmatrix} (-14)a\\2a\end{bmatrix}+\begin{bmatrix} 5b\\(-1)b\end{bmatrix}=\begin{bmatrix} -13\\3\end{bmatrix}\\ $ $\text{Above equation can be solve using substitution and elimination method but it can have infinite no solution.}$


An equation is said to be `Linear equation` if the variable can have exponent of 1 like below:
$\\y = mx + b$

An equation is said to be `Quadratic equation` if the variable can have exponent of 2 like below:
$\\ax^2 + bx + c = 0$


This set can be solved using three theoretical methods:

* Graphical method
* Substitution method
* Elimination method

we will go through the last 2 of them: 

To find the values of unknowns (a,b) in the above equation there can be an infinite no of solution to the above vectors.
**Elimination method**

${10𝑎 + 15𝑏 = -5\\2𝑎 + 3𝑏 = -1 * 5\\10𝑎 + 15𝑏 = -5\\10𝑎 + 15𝑏 = -25\\ \text{Subtract the first equation from the second :}10𝑎 + 15𝑏 = -5\\10𝑎 + 15𝑏 - 10𝑎 - 15𝑏 = -5 - (-25)\\0𝑎 = 20\\0𝑎 = 20\\𝑎 = 0\\ }$

**Substitution method**

${
\text{Solve one of the equations for one of the variables, for example, solve for a in the first equation:}\\
2𝑎 + 3𝑏 = -1\\
2𝑎 = -1 - 3𝑏\\
𝑎 = (-1 - 3𝑏) / 2\\
\text{Substitute the expression for a found in step 1 into the second equation:}
10𝑎 + 15𝑏 = -5\\
10((-1 - 3𝑏) / 2) + 15𝑏 = -5\\
-5 - 15𝑏 + 15𝑏 = -5\\
-5 = -5\\
\text{Solve for b:}
𝑎 = (-1 - 3𝑏) / 2\\
b = (1 + 2𝑎) / 3\\
\text{Substitute the value of b found in step 5 into the expression for a:}
𝑎 = (-1 - 3𝑏) / 2\\
𝑎 = (-1 - 3(-3 / 5)) / 2\\
𝑎 = (1 + 9 / 5) / 2\\
𝑎 = (10 / 5) / 2\\
𝑎 = 2\\
}$


### The two equations above are linearly dependent.

Try to sketch them graphically. What do you see? How may points of intersection are there?

Since the two equations are linearly dependent, graphically they define the same line. Hence there are infinite number of solutions to the set of these equations. Basically, each point on the line (depicted by the blue x) satisfies the equation.
<div style='display:flex'>
<img src='https://i.postimg.cc/Hn2sB0sx/delete.png' style ='width:400px'>
<img src='https://i.postimg.cc/Hn2sB0sx/delete.png' style ='width:400px'>
</div>


<h2 style='background-color:#ccffee; padding:24px;'>Linear Transformation and Matrices</h2>


> Our next step is to understand how to apply matrix arithmetic: to perform operations such as:

        * Matrix Addition
        * Scalar multiplication of a matrix
        * Matrix multiplication

**Matrix addition**
There are only 2 rules of matrix addition:
* Make sure dimensions (rows & columns) of both matrix is equal because matrix 1 would be broadcast over other matrix.
* Make sure we add elements in the correct corresponding index.

**Scalar multiplication of a matrix**

To multiply a matrix by a scalar, we do **not** need to verify

* Dimensions or
* Indices

Simply multiply each element in the matrix by the scalar!
e.g.

$\alpha A=\begin{bmatrix}\alpha1&\alpha2\\\alpha3&\alpha4\end{bmatrix}$



## Quiz

What is the the value of the $ij\text {th}$ element of Matrix D if:

${D=0.2A + (-5)B - 2C \\ a. i=1, j=1 \\ b. i = 2, j=4}$

In [15]:
import numpy as np
import pandas as pd
# Creating 3 matrices and then applying the above operation on it.

A = np.array([[3, 0.6, 4, -3],[-1.3, 4, 0, 8.6],[7, 0, -8, 0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3, 9],[-9, 0, 0, 1]])
C = np.array([[0, 1009, -66.7849, 90],[0, 5, 4, -0.07],[0, 0, 0, 0]])

D = (0.2*A) + (-5*B) - 2*C
D

array([[  -14.4 , -1989.08,   -90.63,  -180.6 ],
       [  -10.26,     0.8 ,   -14.5 ,   -43.14],
       [   46.4 ,     0.  ,    -1.6 ,    -5.  ]])

<h2 style='background-color:#ccffee; padding:24px;'>Multiplication of Square Matrices</h2>

To multiply matrices we have to verify:
* That both of matrices have the same dimension e.g. a= 3x3 b = 3x3

let A and B be two square matrcies of 3 x 3.
$A = \begin{bmatrix}3&1&2 \\ -5&4&1 \\ 0&3&-8 \end{bmatrix}$
$B = \begin{bmatrix}0&5&-1 \\ 3&2&-1 \\ 10&0.5&4 \end{bmatrix}$

$\text{(a) What is the value of element of} c_{23} \text{ of Matrix C where} C = A x B$

$\text{(b) What is the value of element of} c_{23} \text{ of Matrix C where} C = B x A$

Since AxB $\ne$ BxA. We can say that they are not commutative.

Multiplication of Scalars are defintely commutative Since they have single dimension.

<h4>If Column of matrix A is equal to Rows of matrix B then multiplication is possible.<br>
In other words, if P is a matrix with dimensions t x m and Q is a matrix with dimensions m x v then multiplication is possible:
</h4>

A matrix with only one row or one column is a vector.

In [22]:
A = np.array([[3,1,2],[-5,4,1],[0,3,-8]])
B = np.array([[0,5,-1],[3,2,-1],[10,0.5,4]])

# In numpy @ sign is use for matrix multiplication.
print(A@B)
print(np.matmul(B,A))

[[ 23.   18.    4. ]
 [ 22.  -16.5   5. ]
 [-71.    2.  -35. ]]
[[-25.   17.   13. ]
 [ -1.    8.   16. ]
 [ 27.5  24.  -11.5]]


In [23]:
A = np.array([0.6,-15,2,5,98])
B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

##### If C=AxB,

(a) How many rows will C have?

(b) How many columns will C have?

(c) What will be the value of $c_{13}?$

If C=BxA

(d) What will be the value of $c_{13}?$



In [39]:
A@B

array([-102.8,  255.2,  595.6])

Here Green and Red column represent the base vectors in the x-axis and y-axis in the 2D space.
![](https://i.postimg.cc/W1mm6CNc/delete.png)

The **derivative** is a concept in mathematics that measures how much a quantity changes with respect to another quantity. In simple terms, it tells you how quickly a value is changing at a particular point.

For example, if you're driving a car, the speedometer tells you how fast you're going at a given moment. The derivative of speed with respect to time would tell you how quickly your speed is changing - in other words, how quickly you're accelerating or slowing down.