In [37]:
import numpy as np

x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
# Deleting value of first element (0 row 0 column)
del_x = np.delete(x,(0,0))
del_x = del_x.reshape(4,2)
del_x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
# Now delete the first row from the above array
del_x = np.delete(del_x,0,axis=0)
del_x

array([[3, 4],
       [5, 6],
       [7, 8]])

In [40]:
# Delete first column from the above array
del_y = np.delete(del_x,0,axis=1)
del_y


array([[4],
       [6],
       [8]])

In [41]:
# We can't insert rows before the first row for that we need insert function
# appending to the array
a = np.arange(1,6)
a = np.append(a,6)  #Appending 6 element to the last
a = a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
# Adding column to the above ndarray
np.insert(a,0,[11,33,55],axis=1)

array([[11,  1,  2],
       [33,  3,  4],
       [55,  5,  6]])

In [43]:
new_a = a.reshape(3,2)

# Appending two rows [11,22],[33,44]
new_a = np.append(new_a,[[11,22],[33,44]],axis=0)
new_a



array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 22],
       [33, 44]])

In [44]:
# Appending column to array
# new_a = np.append(new_a,[[22,43,34,564,435]],axis=1)

# Above line won't work because of it's dimension below every row differentiate by square brackets
new_a = np.append(new_a,[[22],[44],[66],[222],[444]],axis=1)
new_a

array([[  1,   2,  22],
       [  3,   4,  44],
       [  5,   6,  66],
       [ 11,  22, 222],
       [ 33,  44, 444]])

In [45]:
# inserting values in array

ins = np.arange(12).reshape(4,3)
ins

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
# Insert values along the given axis before the given indices
ins = np.insert(ins,0,[11],axis=0)
ins

array([[11, 11, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
# inserting column at first that we can't do with append method
ins = np.insert(ins,0,[9124],axis=1)
ins

array([[9124,   11,   11,   11],
       [9124,    0,    1,    2],
       [9124,    3,    4,    5],
       [9124,    6,    7,    8],
       [9124,    9,   10,   11]])

In [64]:
# Stacking one array on top of another array
stack1 = np.arange(2,9,2).reshape(2,2)
stack2 = np.linspace(10,19,4,endpoint=False,dtype=int).reshape(2,2)
stack1,stack2

(array([[2, 4],
        [6, 8]]),
 array([[10, 12],
        [14, 16]]))

In [49]:
# Horizontal spliting
hor_split = np.hsplit(stack1,2)
hor_split

[array([[2],
        [6]]),
 array([[4],
        [8]])]

In [50]:
# Vertical spliting
ver_split = np.vsplit(stack1,2)
ver_split

[array([[2, 4]]), array([[6, 8]])]

In [51]:
# Horizontal stacking
hor_stack = np.hstack((stack1,stack2))
hor_stack

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [52]:
# Vertical stacking 
ver_stack = np.vstack((stack1,stack2))
ver_stack

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [53]:
# Horizontal stacking using append numpy function
hor_append_stack = np.append(stack1,stack2,axis=0)
hor_append_stack

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [54]:
# Vertical stacking using append numpy function
ver_append_stack = np.append(stack1,stack2,axis=1)
ver_append_stack 

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [55]:
# Horizontal stacking using insert numpy function

# this code will insert stack1 array before first row of stack2 
hor_insert_stack = np.insert(stack2,0,stack1,axis=0)
hor_insert_stack

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [56]:
# Vertical stacking using insert numpy function

# using insert function we can put array anywhere in the array
ver_insert_stack = np.insert(stack2,2,stack1,axis=1)
ver_insert_stack

array([[10, 12,  2,  6],
       [14, 16,  4,  8]])

<h1 style='color:green;'> Numpy Slicing</h1>
<hr style="height:4px;border-width:2;background-color:green">

In [57]:
arr = np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [58]:
# We want to access only 8, 9, 10 and below all the values column wise to do that we need slicing technique

# Below 1 indicate row and 2 indicate columns we can also mention steps
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [59]:
# Now select all the elements from the third row and return it in rank 2 array
view = arr[2:3].reshape((5,1))

In [60]:
id(view),id(view)


(1486863336144, 1486863336144)

In [61]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [62]:
# Extracting values from diagnal
# The Following command will extract values from 0 index upto the end on diagnol. we can also use indices (-1,0,1,2 etc)
np.diag(arr,k=-1)

array([ 6, 12, 18])

In [63]:
# This function will return unique values from an array and it's indices as well.
np.unique(arr,return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19], dtype=int64))