In [52]:
import numpy as np


In [53]:
# Create a 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
             ])

# Sum of elements along axis=0 (column-wise)
print(np.sum(arr, axis=0))  # Output: [12 15 18]

# Sum of elements along axis=1 (row-wise)
print(np.sum(arr, axis=1))  # Output: [ 6 15 24]


[12 15 18]
[ 6 15 24]


In [54]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
# Boolean expression is needed when we want to select a specific range of elements from an array e.g.
# Selecting values greater than 11 from above array
x|[x>10]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 13, 13, 15],
        [15, 17, 17, 19, 19],
        [21, 21, 23, 23, 25]]], dtype=int32)

In [56]:
# The elements in X that are greater than 10
x[x>10] 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
# The elements in X that less than or equal to 7
x[x<=7]


array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
# The elements in X that are between 10 and 17
x[(x>10) & (x<17)]

array([11, 12, 13, 14, 15, 16])

In [59]:
# Elements that are less than 10 replace it with -1 and greater than 10 replace it with zero
x[x<10] = -1
x[(x>-1) | (x==10) ] = 0
x

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [60]:
y = np.array([4,7,23,9,75,7,5,34,67,99,67,54,32,62,33,22]).reshape(4,4)
y

array([[ 4,  7, 23,  9],
       [75,  7,  5, 34],
       [67, 99, 67, 54],
       [32, 62, 33, 22]])

In [61]:
# This will sort after flattening the array
# np.sort(y)

In [62]:
# sorting array column wise
np.sort(y,axis=0)

array([[ 4,  7,  5,  9],
       [32,  7, 23, 22],
       [67, 62, 33, 34],
       [75, 99, 67, 54]])

In [73]:
print(y)

print('\n=============\n')

# Also return maximum on the zero-axis
print(np.max(y,axis=1))


[[ 4  7 23  9]
 [75  7  5 34]
 [67 99 67 54]
 [32 62 33 22]]


[23 75 99 62]


In [64]:
# Sum of all the element row wise 
print('Row-Wise sum: ',np.sum(y,axis=1))

# Standard deviation of row 1
print('Standard deviation: ',np.std(y,axis=1))

# Average/mean of row 1
print('Average: ',np.mean(y,axis=1))

# Getting values from diagonal of the matrix 'Y'
print('Values on diagnol: ',np.diag(y,k=-1))

Row-Wise sum:  [ 43 121 287 149]
Standard deviation:  [ 7.29297607 28.26105978 16.60383992 14.92271758]
Average:  [10.75 30.25 71.75 37.25]
Values on diagnol:  [75 99 33]


In [65]:
# Performing set operating on Rank 1 and Rank 2 array

# common values in arr1 and arr2 array
arr1 = np.array([6,7,2,8,4])
arr2 = np.array([1,2,3,4,5])
print(np.intersect1d(arr1,arr2))

# union of both arrays
print(np.union1d(arr1,arr2))

[2 4]
[1 2 3 4 5 6 7 8]


In [66]:
# Elements of arr1 that are not in arr2
print(np.setdiff1d(arr1,arr2))

[6 7 8]


In [67]:
# If using unique method then we don't need of sorted function to order the elements
np.unique(arr1)

array([2, 4, 6, 7, 8])

In [68]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
X

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2==1]
Y


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [69]:
"""
Rules of Broadcasting e.g.
x = [1,2,3]

y = [
    [4,5,6],
    [7,8,9],
    ]
by broadcasting x on y numpy will replicate the 'x' array over y matrix means
a single copy of array 'x' would be create for both of the rows in matrix 'y'
That could lead us to inefficient usage of memory if we are working on larger arrays.

Soution: The solution of this problem would be numpy.add() function
"""
# Let's see an example also calculate it's execution time and it's size on memory
import time
import sys

# Creating 1D-Array of which shape is compatible with 2D-Array 
small_arr = np.arange(10000)
big_arr = np.random.rand(10000,10000)

start1 = time.time()
useless = small_arr*big_arr
print("The size of useless: ",sys.getsizeof(useless))
print((time.time()-start1))

# As we can see numpy 
start2 = time.time()
useful = np.dot(small_arr,big_arr)
print("The size of usefull: ",sys.getsizeof(useful))
print(time.time()-start2)



The size of useless:  800000128
0.38562870025634766
The size of usefull:  80112
0.04787111282348633


In [70]:
# @ sign is the shortcut of matrix multiplication

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
%timeit mat1 * mat2

# print(result)

%timeit np.matmul(mat1,mat2)




598 ns ± 22.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.37 µs ± 29.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [124]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third column full of 3s, etc.. 

# Do not change the name of this array. 
# Please don't print anything from your code! The TEST RUN button below will print your array. 

one = np.ones((4,4),dtype=int)
nums = np.arange(1,5,dtype=int)

X =  one * nums

# We can do the same using creating a random or contain any numbers in matrix of shape (4,4) and replace matrix with 
# element column wise e.g.

randArray = np.arange(1,17).reshape(4,4)
randArray


# Now below code will select the first column and will replace it with corresponding values
element = 1
for i in range(4):
    randArray[:,i] = element
    element+=1

# randArray[[0],0] = 2342
randArray


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [72]:
# Finding median of matrix by following it's axis
med = np.arange(12).reshape(3,4)
print(med)

np.median(med,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([1.5, 5.5, 9.5])