In [116]:
import numpy as np
import time
import sys
x = np.random.random(100000)

# Case 1 to check the execution time of program using simple python script
start = time.time()

# Find the average of x using traditional way of python
sum(x)/len(x)

print((time.time()-start)*1000) # I multiply it with 1000 because i wanted the time to be miliseconds

# Case 2 to check the execution time of program using numpy
start = time.time()
np.mean(x)
print((time.time()-start)*1000)


# As we can see below numpy took only 1 miliseconds on contrast python takes 11 miliseconds

11.000394821166992
0.96893310546875


In [117]:
my2d_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# slicing in numpy array
# Below slicing will show us only 2-rows and 3-columns
my2d_array[:2,:3]


array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
num_array = np.arange(12).reshape(3,4)
num_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
num_array[1:3,0:2],num_array[::2,::2]

(array([[4, 5],
        [8, 9]]),
 array([[ 0,  2],
        [ 8, 10]]))

In [120]:
id(num_array[1:3,0:2]),id(num_array), id(num_array[:1])

(2174339874704, 2174339867888, 2174339874704)

In [121]:
# Strides are the number of bytes requires to get to the next element in array
# In the case of 2d array as follows gives the resultant tuple (12,4) means 12 bytes requires to reach to the next row whereas
# 4 means that it requires only 4 bytes to reach to the next column
num_array.strides



(16, 4)

In [122]:
# Above 4 bytes requires because of the datatype of the element which is int32 (means integer will take 32 bit of memory)
# If we convert bits to bytes then ==> 32/8 = 4 bytes
# If we want to store larger integers then we can use int64 although most of work can be done int32
# Int32 is more memory efficient so it's good to use it unless we have a good reason to use int64
sys.getsizeof(num_array), num_array.dtype,num_array.strides


(128, dtype('int32'), (16, 4))

In [123]:
# Creating int64 bit of array 

big_array = np.arange(12,dtype='int64').reshape(3,4)

sys.getsizeof(big_array),big_array.dtype,big_array.strides


(128, dtype('int64'), (32, 8))

In [124]:
# np.iinfo(num_array.dtype).bits
np.iinfo(big_array.dtype).bits,np.iinfo(num_array.dtype).bits

(64, 32)

In [125]:
# Number of dimension this array have
big_array.ndim

2

In [126]:
# Check the size of array
# Below the size means how many elements contains in big_array
big_array.size  

12

In [127]:
# Comparing creation of array using python array module and numpy 
import time
x_time = time.time()
x = np.array([i for i in range(100000)])
x_time = time.time()-x_time

# Now create array using numpy and find it's execution time
y_time = time.time()
y = np.arange(100000)
y_time = time.time() - y_time

x_time/1000 , y_time/1000

(1.6947507858276367e-05, 0.0)

In [128]:
# We can also store numpy array to a file (np.save) and then can upload letter on (np.load)
# np.save('textnumpy',big_array)
# loaded = np.load('textnumpy.npy')
# loaded

In [129]:
# Creating zero matrix
zero = np.zeros((3,3))
ones = np.ones((3,3))
constant = np.full((3,3),2) # create an array with shape (3x3) and replace all the elements with 2

diagnal = np.diag([33,44,55,66]) # create a matrix and fill the diagonal with the given list

identity = np.eye(3,3,dtype=int) # Create identity matrix with shape (3x3)

print(zero , end='\n\n',)
print(ones, end='\n\n')
print(constant, end='\n\n')
print(diagnal, end='\n\n')
print(identity.dtype)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]

[[33  0  0  0]
 [ 0 44  0  0]
 [ 0  0 55  0]
 [ 0  0  0 66]]

int32


In [130]:
arr = np.arange(12)
new_arr = np.reshape(arr,(3,4))
new_arr.reshape((4,3))



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
# Create array with only even number upto 20
even = np.arange(2,21,2,dtype=int).reshape(5,2)
even

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [132]:
# linspace function will create an array of millions of samples from 0-1 or it can be anything 
# below linspace will pick 50 sample between 0-0.1
linespace = np.linspace(0,0.1,50)
linespace

array([0.        , 0.00204082, 0.00408163, 0.00612245, 0.00816327,
       0.01020408, 0.0122449 , 0.01428571, 0.01632653, 0.01836735,
       0.02040816, 0.02244898, 0.0244898 , 0.02653061, 0.02857143,
       0.03061224, 0.03265306, 0.03469388, 0.03673469, 0.03877551,
       0.04081633, 0.04285714, 0.04489796, 0.04693878, 0.04897959,
       0.05102041, 0.05306122, 0.05510204, 0.05714286, 0.05918367,
       0.06122449, 0.06326531, 0.06530612, 0.06734694, 0.06938776,
       0.07142857, 0.07346939, 0.0755102 , 0.07755102, 0.07959184,
       0.08163265, 0.08367347, 0.08571429, 0.0877551 , 0.08979592,
       0.09183673, 0.09387755, 0.09591837, 0.09795918, 0.1       ])

In [133]:
np.random.random(50) # Create 50 random sample between 0 (inclusive) 1 (exclusive)

array([0.66719137, 0.2628631 , 0.35366865, 0.14410339, 0.40524794,
       0.75771918, 0.97757064, 0.13436503, 0.34389272, 0.93904763,
       0.482228  , 0.52470473, 0.79287544, 0.45194136, 0.61295335,
       0.06123284, 0.98023283, 0.77974661, 0.59279062, 0.22237628,
       0.03363522, 0.50385196, 0.46000313, 0.92359811, 0.994709  ,
       0.37739905, 0.45051987, 0.0963721 , 0.12611053, 0.74338447,
       0.48980994, 0.29925868, 0.41124002, 0.20643594, 0.4641492 ,
       0.60322081, 0.89002683, 0.76897724, 0.4597682 , 0.84697272,
       0.03267904, 0.89413204, 0.36404518, 0.76863559, 0.99121543,
       0.55005872, 0.1574923 , 0.15673166, 0.59180049, 0.55946877])

In [134]:
np.random.randint(2,10,50) # Create 50 random sample between 2-10 (10 exclusive)

array([5, 9, 8, 9, 6, 6, 8, 6, 2, 7, 9, 6, 2, 8, 5, 3, 7, 8, 8, 7, 4, 4,
       2, 8, 4, 9, 2, 5, 4, 7, 7, 8, 5, 4, 3, 5, 3, 8, 8, 5, 7, 3, 6, 5,
       5, 7, 3, 9, 7, 6])

In [135]:
ndist = np.random.normal(0,0.1,(1000,1000)) # Create 50 random sample from normal (guasian)distribution
ndist.ndim

2

In [136]:
print('The elements in X have a mean of:', ndist.mean())
print('The maximum value in X is:', ndist.max())
print('The minimum value in X is:', ndist.min())

The elements in X have a mean of: 0.00015258605142367
The maximum value in X is: 0.4705536253474361
The minimum value in X is: -0.4682671096919325


In [137]:
                # Quiz of Numpy array
# Using the Built-in functions you learned about on the
# Above page, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

np.arange(2,33,2).reshape(4,4)



array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [138]:
# Now creating the above array using linspace function
# Below 16 will tell it to pick 16 element in the array
np.linspace(2,33,16).reshape(4,4)

array([[ 2.        ,  4.06666667,  6.13333333,  8.2       ],
       [10.26666667, 12.33333333, 14.4       , 16.46666667],
       [18.53333333, 20.6       , 22.66666667, 24.73333333],
       [26.8       , 28.86666667, 30.93333333, 33.        ]])

In [139]:
big_arrayT = big_array.T # Transposing array using Capital 'T' which stands for Transpose
big_arrayT

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]], dtype=int64)

In [140]:
big_array.strides , big_arrayT.strides

((32, 8), (8, 32))

In [141]:
simple = np.arange(-8,264,2).reshape(17,8)
simple



array([[ -8,  -6,  -4,  -2,   0,   2,   4,   6],
       [  8,  10,  12,  14,  16,  18,  20,  22],
       [ 24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80,  82,  84,  86],
       [ 88,  90,  92,  94,  96,  98, 100, 102],
       [104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146, 148, 150],
       [152, 154, 156, 158, 160, 162, 164, 166],
       [168, 170, 172, 174, 176, 178, 180, 182],
       [184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214],
       [216, 218, 220, 222, 224, 226, 228, 230],
       [232, 234, 236, 238, 240, 242, 244, 246],
       [248, 250, 252, 254, 256, 258, 260, 262]])

In [142]:
# Following code will change dtype of array to 'uint8' which is unsigned integer of 8-bits 
# Means uint8 can only store integer values from 0-255 this type is used for image and video processing

# If we want an element to take less space then integer than we can use unsigned integers. 
# If values are outside 0-255 then elements will start from 0 again like below
new_simple = simple.astype('uint8')
new_simple

array([[248, 250, 252, 254,   0,   2,   4,   6],
       [  8,  10,  12,  14,  16,  18,  20,  22],
       [ 24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80,  82,  84,  86],
       [ 88,  90,  92,  94,  96,  98, 100, 102],
       [104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134],
       [136, 138, 140, 142, 144, 146, 148, 150],
       [152, 154, 156, 158, 160, 162, 164, 166],
       [168, 170, 172, 174, 176, 178, 180, 182],
       [184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214],
       [216, 218, 220, 222, 224, 226, 228, 230],
       [232, 234, 236, 238, 240, 242, 244, 246],
       [248, 250, 252, 254,   0,   2,   4,   6]], dtype=uint8)

In summary `uint8` is used for image processing mostly because pixels takes value between 0-255 and uint is also have range of
0-255 so it's memory efficient and computational faster.

In [143]:
big_array = np.arange(2,32,2).reshape(5,3)
# big_array[big_array > 255] = 255
big_array = big_array.astype(np.uint8)
big_array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]], dtype=uint8)

In [144]:
# Vectroization is the process of performing some action on elements in array e.g.
# we have a vector and we wish to multiple it's magnitude by 3 how that's will look in traditional python way

# In python we have to traverse element by element e.g.
a = [1,2,3]
b = [3*e for e in a]
b


[3, 6, 9]

In [145]:
vecorization = np.arange(1,11).reshape(10,)
vecorization_new = vecorization*2
vecorization_new

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [154]:
# Broadcasting of one array over other e.g

# a1 =  1  2  3
# a2 = 11 11 11
#      44 44 44
#      77 77 77
# =============
# 
a1 = np.array([1,2,3])
a2 = np.array([[11],
               [44],
               [77]])
a1+a2
# Now because of a1 array have the shape of (3,) and a2 have the shape of (3,1) so numpy will expands dimenstions of a2 so that
# each of the array suits one another.

array([[12, 13, 14],
       [45, 46, 47],
       [78, 79, 80]])

In [147]:
# Now if we do the same using vectorization than vectorization will use the brodcasting technique which is much more faster e.g.
# Below 3 will be broadcast on all the elements in array [1,2,3] and multiplication will happen in paralell
a_vector = np.array([1,2,3])
b_vector = a_vector*3
b_vector

array([3, 6, 9])

In [148]:
# x (2, 4, 3)
# y (   4, 1)
# ===========
# z (2, 4, 3)

# Before broadcasting numpy verifies that all dimensions are suitable if either is 1 or None e.g above will be correct
